site_name: BMEVIAUAV23 - Szoftverfejlesztés .NET platformra
site_author: Tóth Tibor, Simon Gábor, Albert István, Szabó Gábor
copyright: Copyright &copy; BME VIK AUT
repo_name: bmeviauav23/aspnetcorebook
repo_url: https://github.com/bmeviauav23/aspnetcorebook
site_url: https://bmeviauav23.github.io/aspnetcorebook/

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  language: hu
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: aut
      primary: aut
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Váltás sötét témára
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Váltás világos témára
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.action.edit
    - content.code.annotate
    - toc.follow
  logo: logo-bme-aut.png
  favicon: favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - extra-sass
  - glightbox
  - git-revision-date-localized:
      # override from docker environment variables
      # not a vanilla yaml syntax, only works with mkdocs.yaml because of pyyaml_env_tag
      enabled: !ENV [IsRevisionDatePluginEnabled, false]
      enable_creation_date: false
      type: timeago
      timezone: Europe/Budapest
      locale: hu
  - git-committers:
      # override from docker environment variables
      # not a vanilla yaml syntax, only works with mkdocs.yaml because of pyyaml_env_tag
      enabled: !ENV [IsAuthorsPluginEnabled, false]
      github_token: !ENV [GITHUB_TOKEN, '']
      repository: bmeviauav23/aspnetcorebook
      branch: master
  - with-pdf:
      author: Tóth Tibor <toth.tibor@vik.bme.hu>; Simon Gábor <simon.gabor@vik.bme.hu>; Szabó Gábor <szabo.gabor@podnet.hu>
      #copyright: ANY TEXT
      #
      cover: true
      back_cover: false
      cover_title: Szoftverfejlesztés .NET platformra gyakorlatok
      cover_subtitle: v1.7 - hetedik kiadás, 2024. június
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: Tartalomjegyzék
      #heading_shift: true
      #toc_level: 4
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      # render_js: true
      # headless_chrome_path: headless-chromium
      #
      output_path: pdf/aspnetcorebook.1.7.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      debug_html: true
      #show_anchors: true
      verbose: true

nav:
  - "Tudnivalók":
      - index.md
      - information/preface.md
      - information/contributing.md
  - "Laborok":
      - seminar/01-csharp1/chapter1.md
      - seminar/02-csharp2/chapter2.md
      - seminar/03-linq/chapter3.md
      - seminar/04-csharp4/chapter4.md
      - seminar/05-aspnetcore1/chapter5.md
      - seminar/06-efcore/chapter6.md
      - seminar/07-restapi/chapter7.md
      - seminar/08-client/chapter8.md
      - seminar/10-test/chapter10.md
  - "Házi feladat":
      - homework/index.md
      - homework/example-spec.md
      - homework/hw-points.md
